#include <vector>
#include <string>

struct WeightedItem {
    std::string item;
    double weight;
    WeightedItem(std::string i, double w) {
        item = i;
        weight = w;
    };
};

std::vector<WeightedItem> PACKS = {
    WeightedItem("RETRY", 22.42),
    WeightedItem("Arcana Pack", 4),
    WeightedItem("Jumbo Arcana Pack", 2),
    WeightedItem("Mega Arcana Pack", 0.5),
    WeightedItem("Celestial Pack", 4),
    WeightedItem("Jumbo Celestial Pack", 2),
    WeightedItem("Mega Celestial Pack", 0.5),
    WeightedItem("Standard Pack", 4),
    WeightedItem("Jumbo Standard Pack", 2),
    WeightedItem("Mega Standard Pack", 0.5),
    WeightedItem("Buffoon Pack", 1.2),
    WeightedItem("Jumbo Buffoon Pack", 0.6),
    WeightedItem("Mega Buffoon Pack", 0.15),
    WeightedItem("Spectral Pack", 0.6),
    WeightedItem("Jumbo Spectral Pack", 0.3),
    WeightedItem("Mega Spectral Pack", 0.07)
};


std::vector<std::string> COMMON_JOKERS = {
    "Joker",
    "Greedy Joker",
    "Lusty Joker",
    "Wrathful Joker",
    "Gluttonous Joker",
    "Jolly Joker",
    "Zany Joker",
    "Mad Joker",
    "Crazy Joker",
    "Droll Joker",
    "Sly Joker",
    "Wily Joker",
    "Clever Joker",
    "Devious Joker",
    "Crafty Joker",
    "Half Joker",
    "Credit Card",
    "Banner",
    "Mystic Summit",
    "8 Ball",
    "Misprint",
    "Raised Fist",
    "Chaos the Clown",
    "Scary Face",
    "Abstract Joker",
    "Delayed Gratification",
    "Gros Michel",
    "Even Steven",
    "Odd Todd",
    "Scholar",
    "Business Card",
    "Supernova",
    "Ride the Bus",
    "Egg",
    "Runner",
    "Ice Cream",
    "Splash",
    "Blue Joker",
    "Faceless Joker",
    "Green Joker",
    "Superposition",
    "To Do List",
    "Cavendish",
    "Red Card",
    "Square Joker",
    "Riff-raff",
    "Photograph",
    "Reserved Parking",
    "Mail In Rebate",
    "Hallucination",
    "Fortune Teller",
    "Juggler",
    "Drunkard",
    "Golden Joker",
    "Popcorn",
    "Walkie Talkie",
    "Smiley Face",
    "Golden Ticket",
    "Swashbuckler",
    "Hanging Chad",
    "Shoot the Moon"
};

std::vector<std::string> UNCOMMON_JOKERS = {
    "Joker Stencil",
    "Four Fingers",
    "Mime",
    "Ceremonial Dagger",
    "Marble Joker",
    "Loyalty Card",
    "Dusk",
    "Fibonacci",
    "Steel Joker",
    "Hack",
    "Pareidolia",
    "Space Joker",
    "Burglar",
    "Blackboard",
    "Sixth Sense",
    "Constellation",
    "Hiker",
    "Card Sharp",
    "Madness",
    "Seance",
    "Vampire",
    "Shortcut",
    "Hologram",
    "Cloud 9",
    "Rocket",
    "Midas Mask",
    "Luchador",
    "Gift Card",
    "Turtle Bean",
    "Erosion",
    "To the Moon",
    "Stone Joker",
    "Lucky Cat",
    "Bull",
    "Diet Cola",
    "Trading Card",
    "Flash Card",
    "Spare Trousers",
    "Ramen",
    "Seltzer",
    "Castle",
    "Mr. Bones",
    "Acrobat",
    "Sock and Buskin",
    "Troubadour",
    "Certificate",
    "Smeared Joker",
    "Throwback",
    "Rough Gem",
    "Bloodstone",
    "Arrowhead",
    "Onyx Agate",
    "Glass Joker",
    "Showman",
    "Flower Pot",
    "Merry Andy",
    "Oops! All 6s",
    "The Idol",
    "Seeing Double",
    "Matador",
    "Satellite",
    "Cartomancer",
    "Astronomer",
    "Bootstraps"
};

std::vector<std::string> RARE_JOKERS = {
    "DNA",
    "Vagabond",
    "Baron",
    "Obelisk",
    "Baseball Card",
    "Ancient Joker",
    "Campfire",
    "Blueprint",
    "Wee Joker",
    "Hit the Road",
    "The Duo",
    "The Trio",
    "The Family",
    "The Order",
    "The Tribe",
    "Stuntman",
    "Invisible Joker",
    "Brainstorm",
    "Drivers License",
    "Burnt Joker"
};

std::vector<std::string> LEGENDARY_JOKERS = {
    "Canio",
    "Triboulet",
    "Yorick",
    "Chicot",
    "Perkeo"
};